server:
  port: 8080
spring:
  application:
    name: "Demo"
  devtools:
    add-properties: false
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb+srv://desarrollo01:juank9225@cluster0.omffl.mongodb.net/persona?retryWrites=true&w=majority"
